### ISSUE TITLE
Cannot go to AuthConfig resource

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/kuadrant-console-plugin#149]
When trying to go to an AuthConfig resource from the **Policy Topology** view, the action fails and the following error is raised in the console:

```
GVK mapping not found for resource type: AuthConfig
```

<img width="1677" alt="Screenshot 2024-11-12 at 17 17 38" src="https://github.com/user-attachments/assets/2d0ae782-e62d-4f03-9d68-9129e9c40fc6">

**Comment by jasonmadigan** [comment]
Resolved in v0.0.10 (note to self: need to circle back to others about what show/hide/group with our internals)
