### ISSUE TITLE
Plugin installation + docs

### ISSUE THREAD

**Issue by jasonmadigan** [Kuadrant/kuadrant-console-plugin#46]
Add to kuadrant-operator
- Check for OCP (`ConsolePlugin` CRD existence), only enable for OCP
- Figure out bundling + builds/CI
- Doc updates to enable/install the plugin

See https://github.com/openshift/enhancements/blob/master/enhancements/console/dynamic-plugins.md#delivering-plugins

**Comment by andersonsilva87** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by jasonmadigan** [comment]
@david-martin @R-Lawton added a quick issue on figuring out installation

**Comment by jasonmadigan** [comment]
![Screenshot 2024-09-25 at 16 56 23](https://github.com/user-attachments/assets/0e494e84-6639-4c35-bcac-5230b6499af2)

Two WIP branches in kuadrant-operator (manifest applying) and console-plugin (builds)

**Comment by jasonmadigan** [comment]
https://github.com/Kuadrant/console-plugin/compare/main...jasonmadigan:console-plugin:console-plugin-install?expand=1
https://github.com/Kuadrant/kuadrant-operator/compare/main...jasonmadigan:kuadrant-operator:console-plugin-install?expand=1

**Comment by jasonmadigan** [comment]
https://github.com/Kuadrant/console-plugin/pull/76

Have setup GH action to push merges/pushes to main to quay:

https://quay.io/repository/kuadrant/console-plugin
