### ISSUE TITLE
Update the RateLimitPolicy create form with changes to API for kuadrant v1

### ISSUE THREAD

**Issue by david-martin** [Kuadrant/kuadrant-console-plugin#68]
Depends on:
- `routeSelector` changes in https://github.com/Kuadrant/kuadrant-operator/issues/810
- `when` changes in https://github.com/Kuadrant/kuadrant-operator/issues/800

See conversation in slack at https://kubernetes.slack.com/archives/C05J0D0V525/p1726148541588629 for additional context.

This is a follow up to the changes in #63 (#31) where UI elements were held back to avoid redundant work.
An interim solution was used where an 'info' message is shown with text that directs the user to the yaml view if they want to set more complex limits configuration.

**Comment by maleck13** [comment]
setting as a must as it wont work without it

**Comment by R-Lawton** [comment]
With the new change to remove the form for RLP and re evaluate how we want to show the complexity of the rlp this isn't needed for for 1.0

**Comment by jasonmadigan** [comment]
yeah, think our late change to drop form editing of RLP's sort of anulls this for now. Will be something we'll have to tackle when we bring back a form view RLP (and AP) post 1.0
