### ISSUE TITLE
Change the namespace selector in the policy create/update views

### ISSUE THREAD

**Issue by R-Lawton** [Kuadrant/kuadrant-console-plugin#92]
Change the in-form namespace selector to the top level nav built in selector

**Comment by jasonmadigan** [comment]
- [ ] `DNSPolicy`
- [ ] `TLSPolicy`
- [ ] `AuthPolicy`
- [ ] `RateLimitPolicy`

**Comment by jasonmadigan** [comment]
PRs:

https://github.com/Kuadrant/kuadrant-console-plugin/pull/96

**Comment by jasonmadigan** [comment]
Note: remove src/components/namespace/NamespaceSelect.tsx after DNSPolicy update lands
